# Generated by Django 5.1 on 2024-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
            ],
        ),
    ]
